language: java

jdk:
  - openjdk6

services:
  - mysql

before_script:
  - mysql -u root < src/main/resources/sql/access.sql
  - mysql -u root < src/main/resources/sql/schema.sql

script: mvn test

notifications:
  email:
    - tomasz.ducin@gmail.com

